create_clock -name clk -period 20.000 [get_ports clk_PAD]
set_clock_uncertainty 0.25 [get_clocks clk]
set_input_transition 0.15 [all_inputs]
set_input_delay 2.0 -clock clk [remove_from_collection [all_inputs] [get_ports clk_PAD]]
set_output_delay 4.0 -clock clk [all_outputs]
set_load 0.033442 [all_outputs]
set_false_path -from [get_ports {rst_n_PAD boot_sclk_PAD boot_cs_n_PAD boot_mosi_PAD boot_mode_PAD}]
