meta:
  version: 3
  flow: Chip
  substituting_steps:
    Checker.IllegalOverlap: null
DESIGN_NAME: chip_top
VERILOG_FILES:
  - dir::../src/chip_top.sv
  - dir::../src/chip_core.sv
  - dir::../src/quasi_soc_core.sv
  - dir::../rtl/upstream/alu.v
  - dir::../rtl/upstream/register_file.v
  - dir::../rtl/upstream/rv32m.v
  - dir::../rtl/upstream/privilege.v
  - dir::../rtl/upstream/riscv-multicyc.v
VERILOG_INCLUDE_DIRS: [dir::../rtl]
VERILOG_DEFINES: [FUNCTIONAL, RV32M, IRQ_EN]
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

#PAD_SOUTH: [clk_pad, rst_n_pad, "inputs\\[0\\].input_pad", "inputs\\[1\\].input_pad", "inputs\\[2\\].input_pad", "inputs\\[3\\].input_pad"]
#PAD_EAST: ["inputs\\[4\\].input_pad", "inputs\\[5\\].input_pad", "inputs\\[6\\].input_pad", "inputs\\[7\\].input_pad", vdd_pad, vss_pad]
#PAD_NORTH: ["outputs\\[7\\].output_pad", "outputs\\[6\\].output_pad", "outputs\\[5\\].output_pad", "outputs\\[4\\].output_pad", iovdd_pad, iovss_pad]
#PAD_WEST: ["outputs\\[3\\].output_pad", "outputs\\[2\\].output_pad", "outputs\\[1\\].output_pad", "outputs\\[0\\].output_pad"]

PAD_SOUTH: [clk_pad, rst_n_pad, "inputs[0].input_pad", "inputs[1].input_pad", "inputs[2].input_pad", "inputs[3].input_pad"]
PAD_EAST: ["inputs[4].input_pad", "inputs[5].input_pad", "inputs[6].input_pad", "inputs[7].input_pad", vdd_pad, vss_pad]
PAD_NORTH: ["outputs[7].output_pad", "outputs[6].output_pad", "outputs[5].output_pad", "outputs[4].output_pad", iovdd_pad, iovss_pad]
PAD_WEST: ["outputs[3].output_pad", "outputs[2].output_pad", "outputs[1].output_pad", "outputs[0].output_pad"]

PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc
VDD_NETS: [VDD]
GND_NETS: [VSS]
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/p2c
CLOCK_PERIOD: 20.0
FP_SIZING: absolute
DIE_AREA: [0, 0, 1400, 1400]
CORE_AREA: [365, 365, 1035, 1035]
PL_TARGET_DENSITY_PCT: 35
GRT_ALLOW_CONGESTION: true
PDN_CORE_RING: true
PDN_CORE_RING_CONNECT_TO_PADS: true
PDN_ENABLE_PINS: false
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5
MAGIC_EXT_UNIQUE: notopports
PAD_BONDPAD_NAME: bondpad_70x70_novias
EXTRA_GDS: [dir::../ip/bondpad_70x70_novias/gds/bondpad_70x70_novias.gds]
EXTRA_LEFS: [dir::../ip/bondpad_70x70_novias/lef/bondpad_70x70_novias.lef]
IGNORE_DISCONNECTED_MODULES: [bondpad_70x70_novias]
PDN_CFG: dir::pdn_cfg.tcl
MAGIC_GDS_FLATGLOB: ["lvsres_*", "VIA_M1_*", "VIA_M2_*", "*_CELL_CORNER", "RSC_*", "*_CELL_SUB"]

